# Generated by Django 4.2.13 on 2026-02-26 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transcriptchunk',
            name='duration',
            field=models.FloatField(blank=True, help_text='Duration in seconds (e.g. YouTube segment duration)', null=True),
        ),
    ]
