# Generated by Django 4.2.13 on 2026-03-02 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0002_add_duration_to_transcript_chunk'),
    ]

    operations = [
        migrations.AddField(
            model_name='questioncache',
            name='llm_source',
            field=models.CharField(db_index=True, default='openai', max_length=20),
        ),
        migrations.AlterField(
            model_name='questioncache',
            name='question_embedding',
            field=models.TextField(blank=True, default='[]', help_text='JSON list of 1536 floats'),
        ),
    ]
