# Generated by Django 4.2.13 on 2026-03-03 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_engine', '0003_add_llm_source_to_question_cache'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questioncache',
            name='llm_source',
        ),
        migrations.AddField(
            model_name='transcriptchunk',
            name='embedding_provider',
            field=models.CharField(blank=True, db_index=True, help_text="'openai' or 'gemini' - which model produced the embedding", max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='questioncache',
            name='question_embedding',
            field=models.TextField(help_text='JSON list of 1536 floats'),
        ),
        migrations.AlterField(
            model_name='transcriptchunk',
            name='embedding',
            field=models.TextField(help_text='JSON list of floats from embedding model'),
        ),
    ]
